comilonGo/comilonGo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
]

comilonGo/core/urls.py
from django.urls import path
from .views import index,menu,producto,admin_productos,crear_producto,mod_producto,del_producto

urlpatterns = [
    path('',index,name="index"),
    path('index.html',index,name="index"),
    path('menu.html',menu,name="menu"),
    path('producto.html',producto,name="producto"),
    path('admin_productos.html',admin_productos,name="admin_productos"),
    path('crear_producto.html',crear_producto,name="crear_producto"),
    path('mod_producto.html/<id>',mod_producto,name="mod_producto"),
    path('del_producto.html/<id>',del_producto,name="del_producto"),
]

comilonGo/core/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model):
    idCategoria = models.IntegerField(primary_key=True,verbose_name='Id de categoria')
    nombreCategoria = models.CharField(max_length=50, verbose_name='Nombre de la Categoria')

    def __str__(self):
        return self.nombreCategoria

class Producto(models.Model):
    codigo = models.CharField(max_length=6,primary_key=True,verbose_name='Codigo')
    descripcion = models.CharField(max_length=20,verbose_name='Descripcion')
    precio = models.CharField(max_length=12, null=False,blank=False, verbose_name='Precio')
    imagen = models.CharField(max_length=250,null=True,blank=False, verbose_name='Imagen')
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)

    def __str__(self):
        return self.codigo

comilonGo/core/forms.py
from django import forms
from django.forms import ModelForm
from .models import Producto

class ProductoForm(ModelForm):

    class Meta:
        model = Producto
        fields = ['codigo','descripcion','precio','imagen','categoria']

comilonGo/core/views.py
from django.shortcuts import render, redirect
from .models import Producto, Categoria
from .forms import ProductoForm


def index(request):

    productos = Producto.objects.all()

    datos = {
        'productos' : productos
    }

    return render(request,'core/index.html',datos)

def menu(request):
    return render(request,'core/menu.html')

def producto(request):

    categorias = Categoria.objects.all()
    productos = Producto.objects.all()
    
    datos = {

        'categorias' : categorias,
        'productos' : productos
        
    }

    return render(request,'core/producto.html',datos)

def admin_productos(request):

    categorias = Categoria.objects.all()
    productos = Producto.objects.all()
    
    datos = {
        'categorias' : categorias,
        'productos' : productos
        
    }
    return render(request, 'core/admin_productos.html', datos)

def crear_producto(request):

    datos = {
        'form' : ProductoForm()
    }

    if request.method=='POST':
        
        formulario = ProductoForm(request.POST)
        codigoForm = formulario.data['codigo']

        try:
            codigoEncontrado = Producto.objects.get(codigo=codigoForm).codigo

        except Producto.DoesNotExist:
            codigoEncontrado = None

        if codigoEncontrado != None:

            datos['mensaje'] = "Ya existe el codigo"
            
        else:

            if formulario.is_valid:
 
                formulario.save()

                datos['mensaje'] = "Producto guardado correctamente"

    return render(request,'core/crear_producto.html', datos)

def mod_producto(request,id):

    datos = {
        
    }
    
    datos['mensaje'] = ""
    producto = Producto.objects.get(codigo=id)

    if request.method=='POST':

        formulario = ProductoForm(data=request.POST,instance=producto)

        if formulario.is_valid:
            if Producto.objects.get(codigo=id) != formulario.data['codigo']:

                formulario.save()

                datos['mensaje'] = "Producto Modificado Correctamente"

    

    datos['form'] = ProductoForm(instance=producto)

    return render(request, 'core/mod_producto.html',datos)

def del_producto(request,id):

    producto = Producto.objects.get(codigo=id)

    producto.delete()

    return redirect(to="../admin_productos.html")

comilonGo/core/templates/core/crear_producto.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    {% load static %}
    <link href="{% static 'core/css/style.css' %}" rel="stylesheet">

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->

    
    

    <script type="text/javascript">

      
      $(document).ready(function(){

        

        var mensaje = "{{mensaje}}";

        if (mensaje){
          $("#correcto").show();
        }

        $("#volver").click(function(){

                   

          if($("#id_codigo").val().trim().length>=1 || $("#id_descripcion").val().trim().length>=1 || $("#id_precio").val().trim().length>=1 || $("#id_imagen").val().trim().length>=1){

            if (confirm('Tiene campos con datos,¿Está seguro de volver?')) {
              window.location.href = "./admin_productos.html";
            }
            
          } 
          
          else {  
            window.location.href = "./admin_productos.html";
          }
 
          
        });

        
  
        
      });
    </script>
       

    <title>Comilon GO!!</title>
  </head>
  <body class="container fondoBodyAdmin">

    <div class="main-container">  

      <!-- Para los iconos del footer -->
      <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="bootstrap" viewBox="0 0 118 94">
          <title>Bootstrap</title>
          <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
        </symbol>
        <symbol id="facebook" viewBox="0 0 16 16">
          <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
        </symbol>
        <symbol id="instagram" viewBox="0 0 16 16">
            <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
        </symbol>
        <symbol id="twitter" viewBox="0 0 16 16">
          <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
        </symbol>
      </svg>
      


       <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-light colorNavbar">

      <a class="navbar-brand" href="./index.html"><img src="{% static 'core/img/Logo normal.png' %}" alt="" height="120" width="150"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
              <a class="nav-link h5" href="./index.html">Inicio Página <span class="sr-only">(current)</span></a>
            </li>
            
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle h5" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-expanded="false">
                Productos
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

                <a class="dropdown-item" href="./admin_productos.html">Ver Productos</a>
                <a class="dropdown-item" href="./crear_producto.html">Crear Productos</a>
                


              </div>
            </li>

            
        </ul>
      </div>
    </nav>

     

     
    <section class="mb-4">

        <!--titulo-->
        <br>
        <div class="rowEditado container-fluid ">
            <div class="col-md-12 text-center">
              <img  src="{% static 'core/img/admin_crear.png' %}" class="img-fluid img-resposive" alt="titulo contacto" >
            </div>
        </div>
        <br>

        <!-- Contenido-->
        <p class="text-center w-responsive mx-auto mb-5"></p>

        <div class="rowEditado container-fluid justify-content-md-center">

          <div class="col-md-9 mb-md-0 mb-5 table-responsive">
                
            <div class="container">
                
                <form action="" method="post" id="formulario">
                    {% csrf_token %}
                  <div class="form-group">
                    {{ form.as_table }}
                  </div>
                  <div class="text-center ">
                    <input type="submit" value="Enviar" class="btn btn-success" id="enviar">
                    <input type="reset" value="Limpiar" class="btn btn-info" id="limpiar">
                  </div>
                  <div id="error" class="alert alert-danger" role="alert" style="display: none;"></div>
                </form>
                <div id="correcto" class="alert alert-success" role="alert" style="display: none;">{{mensaje}}</div>
              </div>

              <button id="volver" class="btn btn-primary" role="button" onclick="">Volver Listado</button>
              
                
          </div>

        </div>
    </section>

    

    
    
    
    <!-- Footer -->
    <div class="container bg-light">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
          
          <div class="col-12 col-md-4 col-lg-4 d-flex align-items-center">
            
            <span class="text-muted">Comilon GO!! 2022&copy;</span>
          </div>
  
          <div class="col-12 col-md-4 col-lg-4 align-items-center text-center">
            <b class="text-muted " >Comilon GO!! &copy;</b><br>
            <b class="text-muted" > Alameda 333, Viña del Mar</b><br>
            <b class="text-muted" > contacto@comilongo.cl</b><br>
            <b class="text-muted " >+56 9 41528596 </b>
          </div>
      
          <ul class="nav col-12 col-md-4 col-lg-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-muted" href="https://www.twitter.com/comilon_go"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
            <li class="ms-3"><a class="text-muted" href="https://www.instagram.com/comilon_go"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
            <li class="ms-3"><a class="text-muted" href="https://www.facebook.com/comilon_go"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>
          </ul>
        </footer>
      </div>


    

  </div>
  </body>
</html>

comilonGo/core/templates/core/menu.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    
    
    <!-- Optional Javacript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    

    <link rel = "stylesheet" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css">
    <script src = "https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js">
    </script>
    <script src = "https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js">
    </script>

{% load static %}
<link href="{% static 'core/css/style.css' %}" rel="stylesheet">
    

    <title>Comilon GO!!</title>
  </head>
  <body class="container fondoBody">


    <div class="main-container">

        <!-- Para los iconos del footer -->
      <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="bootstrap" viewBox="0 0 118 94">
          <title>Bootstrap</title>
          <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
        </symbol>
        <symbol id="facebook" viewBox="0 0 16 16">
          <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
        </symbol>
        <symbol id="instagram" viewBox="0 0 16 16">
            <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
        </symbol>
        <symbol id="twitter" viewBox="0 0 16 16">
          <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
        </symbol>
      </svg>

        <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-light colorNavbar">

        <a class="navbar-brand" href="./index.html"><img src="{% static 'core/img/Logo normal.png' %}" alt="" height="120" width="150"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link h5" href="./index.html">Inicio <span class="sr-only">(current)</span></a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link h5" href="./menu.html">Menú</a>
              </li>
              <li class="nav-item">
                <a class="nav-link h5" href="./producto.html">Producto</a>
              </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle h5" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-expanded="false">
                Restaurantes
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                
                <a class="dropdown-item disabled" href="#"><img src="{% static 'core/img/f567b1_48c1b8bcf6d94043a35f79fb42b772b3_mv2.gif' %}" height="50" alt=""></a>
              </div>
            </li>
          </ul>
        </div>
      </nav>

      <!-- Contenido-->

      <div class="rowEditado ">
        <div class="col ">        
        <img src="{% static 'core/img/banner.png' %}" style="border: transparent; border-radius: 50px;" class="img-fluid container" alt="...">
        
      </div>
      
      </div>
    
        <div class="rowEditado ">
            <div class="col ">        
              <img style="border: transparent; border-radius: 50px;" src="{% static 'core/img/menu.png' %}" class="img-fluid container" alt="...">
            
            </div>
        </div>

       <!-- Footer -->
    <div class="container bg-light">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
          
          <div class="col-12 col-md-4 col-lg-4 d-flex align-items-center">
            
            <span class="text-muted">Comilon GO!! 2022&copy;</span>
          </div>
  
          <div class="col-12 col-md-4 col-lg-4 align-items-center text-center">
            <b class="text-muted " >Comilon GO!! &copy;</b><br>
            <b class="text-muted" > Alameda 333, Viña del Mar</b><br>
            <b class="text-muted" > contacto@comilongo.cl</b><br>
            <b class="text-muted " >+56 9 41528596 </b>
          </div>
      
          <ul class="nav col-12 col-md-4 col-lg-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-muted" href="https://www.twitter.com/comilon_go"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
            <li class="ms-3"><a class="text-muted" href="https://www.instagram.com/comilon_go"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
            <li class="ms-3"><a class="text-muted" href="https://www.facebook.com/comilon_go"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>
          </ul>
        </footer>


    </div>
    


  </body>
</html>